### ISSUE TITLE
Thermostat labels missing, Paper UI

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#108] opened 2017-11-13 01:30 UTC
The Paper UI is often used for troubleshooting issues with things. All of the omnilink items have a label (name) shown in the Paper UI except for the thermostats.

**Comment by BCS-JonW** [comment] 2017-11-13 23:02
Here's a screenshot of my PaperUI showing some of the thermostats with missing labels.

![hai_thermostats_paperui](https://user-images.githubusercontent.com/7365166/32753907-98c1e4c2-c883-11e7-8aeb-d1be757a7b4a.PNG)

**Comment by boc-tothefuture** [comment] 2017-12-04 12:02
Is this still an issue?  I don't see it on my system - they all have labels.

**Comment by boc-tothefuture** [comment] 2017-12-15 02:10
@swamiller -
  Can we close this?  I just tried on the latest build after discovery with a totally cleaned out system and I can't reproduce it anymore.

**Comment by swamiller** [comment] 2017-12-15 02:37
This isn't a big deal but I just did a fresh install and here is how the thermostats are discovered:

![image](https://user-images.githubusercontent.com/17254439/34024188-76ad2380-e10e-11e7-8d8b-5c23f6cb1419.png)

The label doesn't come across like all of the other things. 

Not a show stopper or a big deal, just an anomaly for the thermostats.

**Comment by boc-tothefuture** [comment] 2017-12-15 10:34
The name for the thermostat was coming across as null. This was in the underlying jomnilink library (so not a new defect).  I pushed a change to jomnilink and put in a PR to here to consume the new library.
Looks good on my side - if you could validate when the PR gets merged, I would appreciate it.

**Comment by swamiller** [comment] 2017-12-16 03:06
I cleaned out my OH database and loaded the latest binding version.  Thermostats don't autodiscover at all now.  I can manually force the setup and the items will link up to my .items file but the thermostat is stuck in "Initializing" until I restarted a couple times.

**Comment by boc-tothefuture** [comment] 2017-12-16 11:19
@swamiller - I can't duplicate this issue.  :(   
I just started with a clean system (in the dev environment) ran discovery, it found both T-Stats and I could add them as Things.  

I am curious if anyone else is seeing the issue?  @craigham or @BCS-JonW ?  That would help me debug it.

**Comment by craigham** [comment] 2017-12-16 14:00
I don't have thermos hooked up to my omnilink.

**Comment by BCS-JonW** [comment] 2017-12-16 21:06
Using PaperUI, I deleted my thermostats, then re-ran discovery and they came right back in - name/label intact.

**Comment by swamiller** [comment] 2017-12-16 23:45
Ok, I’ll try again on a clean install and get back with you.

**Comment by swamiller** [comment] 2017-12-20 02:12
Tested on a clean install, works good.  Thank you very much, @boc-tothefuture!  Excellent work!

Ok to close, from my side.

**Comment by boc-tothefuture** [comment] 2017-12-20 02:27
@craigham - please close.

**Comment by craigham** [comment] 2017-12-20 03:09
@boc-tothefuture nice work.  closing.

**Closed by craigham** 2017-12-20 03:09 UTC
